54 emulate remote controller
Team-Isaac-Polito/reseq_ros2 pull request #63
Opened 2024-12-10 13:23 UTC by Harry0288

2024-12-12 16:46 UTC, luca-byte reviewed
Good start. 💯 

Checks are not passing.

2024-12-12 16:46 UTC, luca-byte commented on reseq_ros2/reseq_ros2/emulator_monitor.py
Are you sure that we need this kind of node?

2024-12-12 16:46 UTC, luca-byte commented on reseq_ros2/reseq_ros2/emulator_trajectory.py
This is just a fixed trajectory, right?

2024-12-13 16:30 UTC, Harry0288 commented on reseq_ros2/reseq_ros2/emulator_trajectory.py
Correct

2024-12-13 16:30 UTC, Harry0288 commented on reseq_ros2/reseq_ros2/emulator_monitor.py
Deleted

2024-12-17 22:04 UTC, luca-byte requested changes
I am sure that this code is able to complete the task, however in this review I would like you to reflect more on the stylistic / design choices.

In my opinion (as an external viewer) the implementation is quite messy (there are many unused variables and very specific lines of code which are incomprehensible at first sight). Moreover it is extremely noticeable the complete absence of documentation, that in combination with a really complex code (the reading loop has an extremely complex conditional structure) makes it quite impossible (at least to me) to understand what the code is doing, even superficially. 

Please, do not take this review negatively, but as a reminder that 1) when we are writing code and it becomes complex, we have always to remember that others have not worked extensively on it and they do not know how it works 2) we should always try to keep the codebase as simple as possible (KISS pattern) (within specifications) otherwise it is very easy to forget pieces and it is a short leap before having _spaghetti code_

2025-03-26 15:20 UTC, luca-byte approved these changes
LGTM 💯

2025-03-26 16:44 UTC, merged